<a href="https://colab.research.google.com/github/Rubiknow/Brief-Sales-Report/blob/main/Brief_Sales_Reports_Data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Import packages for the Analysis

In [41]:
import pandas as pd
import os
import warnings
warnings.filterwarnings('ignore')

In [42]:
#Import Sales data 
sales_data = ('/content/work_all_data (1).xlsx')

In [43]:
# Convert Excel file to Dataframe using Pandas
df = pd.read_excel(sales_data)
df.head(5)

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address
0,236670,Wired Headphones,2,11.99,2019-08-31 22:21:00,"359 Spruce St, Seattle, WA 98101"
1,236671,Bose SoundSport Headphones,1,99.99,2019-08-15 15:11:00,"492 Ridge St, Dallas, TX 75001"
2,236672,iPhone,1,700,2019-08-06 14:40:00,"149 7th St, Portland, OR 97035"
3,236673,AA Batteries (4-pack),2,3.84,2019-08-29 20:59:00,"631 2nd St, Los Angeles, CA 90001"
4,236674,AA Batteries (4-pack),2,3.84,2019-08-15 19:53:00,"736 14th St, New York City, NY 10001"

In [44]:
# Lets quicly see the content of our df
print(f'Data contain {df.shape[0]} records and {df.shape[1]} columns.')

Data contain 186850 records and 6 columns.

In [45]:
# Check for Null values
df.isnull().sum()

Order ID            545
Product             545
Quantity Ordered    545
Price Each          545
Order Date          545
Purchase Address    545
dtype: int64

In [46]:
# Drop all null values from the dataset
df1 = df.dropna()

In [47]:
df1.isnull().sum()

Order ID            0
Product             0
Quantity Ordered    0
Price Each          0
Order Date          0
Purchase Address    0
dtype: int64

In [48]:
# View Data types
df1.dtypes

Order ID            object
Product             object
Quantity Ordered    object
Price Each          object
Order Date          object
Purchase Address    object
dtype: object

In [49]:
#Find and delete 'Or'
df1 = df1[df1['Order Date'].str[0:2] != 'Or']

In [50]:
# Convert Order Quantity ordered, Price each, order date to the right variables
df1['Quantity Ordered'] = df1['Quantity Ordered'].astype('int')
df1['Price Each'] = df1['Price Each'].astype('float')
df1['Order Date'] = pd.to_datetime(df1['Order Date'])

In [51]:
df1.dtypes

Order ID                    object
Product                     object
Quantity Ordered             int64
Price Each                 float64
Order Date          datetime64[ns]
Purchase Address            object
dtype: object

In [52]:
# Add a month column
df1['Month'] = df1['Order Date'].dt.month

In [53]:
df1.head()

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address,Month
0,236670,Wired Headphones,2,11.99,2019-08-31 22:21:00,"359 Spruce St, Seattle, WA 98101",8
1,236671,Bose SoundSport Headphones,1,99.99,2019-08-15 15:11:00,"492 Ridge St, Dallas, TX 75001",8
2,236672,iPhone,1,700.00,2019-08-06 14:40:00,"149 7th St, Portland, OR 97035",8
3,236673,AA Batteries (4-pack),2,3.84,2019-08-29 20:59:00,"631 2nd St, Los Angeles, CA 90001",8
4,236674,AA Batteries (4-pack),2,3.84,2019-08-15 19:53:00,"736 14th St, New York City, NY 10001",8

In [54]:
# Add a month name column
df1['Month Name'] = df1['Order Date'].dt.month_name()
df1.head()

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address,Month,Month Name
0,236670,Wired Headphones,2,11.99,2019-08-31 22:21:00,"359 Spruce St, Seattle, WA 98101",8,August
1,236671,Bose SoundSport Headphones,1,99.99,2019-08-15 15:11:00,"492 Ridge St, Dallas, TX 75001",8,August
2,236672,iPhone,1,700.00,2019-08-06 14:40:00,"149 7th St, Portland, OR 97035",8,August
3,236673,AA Batteries (4-pack),2,3.84,2019-08-29 20:59:00,"631 2nd St, Los Angeles, CA 90001",8,August
4,236674,AA Batteries (4-pack),2,3.84,2019-08-15 19:53:00,"736 14th St, New York City, NY 10001",8,August

In [55]:
# Extract the City and State ID from the purchase address
df1['City'] = df1['Purchase Address'].str.split(",").str.get(1)
df1['State ID'] = df1['Purchase Address'].str.split(" ").str.get(-2)
df1.head()

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address,Month,Month Name,City,State ID
0,236670,Wired Headphones,2,11.99,2019-08-31 22:21:00,"359 Spruce St, Seattle, WA 98101",8,August,Seattle,WA
1,236671,Bose SoundSport Headphones,1,99.99,2019-08-15 15:11:00,"492 Ridge St, Dallas, TX 75001",8,August,Dallas,TX
2,236672,iPhone,1,700.00,2019-08-06 14:40:00,"149 7th St, Portland, OR 97035",8,August,Portland,OR
3,236673,AA Batteries (4-pack),2,3.84,2019-08-29 20:59:00,"631 2nd St, Los Angeles, CA 90001",8,August,Los Angeles,CA
4,236674,AA Batteries (4-pack),2,3.84,2019-08-15 19:53:00,"736 14th St, New York City, NY 10001",8,August,New York City,NY

In [59]:
# Extract Hour from the Order Date Column
df1['Hour'] = df1['Order Date'].dt.hour
df1['Day'] = df1['Order Date'].dt.day_name()
df1.head()

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address,Month,Month Name,City,State ID,Hour,Day
0,236670,Wired Headphones,2,11.99,2019-08-31 22:21:00,"359 Spruce St, Seattle, WA 98101",8,August,Seattle,WA,22,Saturday
1,236671,Bose SoundSport Headphones,1,99.99,2019-08-15 15:11:00,"492 Ridge St, Dallas, TX 75001",8,August,Dallas,TX,15,Thursday
2,236672,iPhone,1,700.00,2019-08-06 14:40:00,"149 7th St, Portland, OR 97035",8,August,Portland,OR,14,Tuesday
3,236673,AA Batteries (4-pack),2,3.84,2019-08-29 20:59:00,"631 2nd St, Los Angeles, CA 90001",8,August,Los Angeles,CA,20,Thursday
4,236674,AA Batteries (4-pack),2,3.84,2019-08-15 19:53:00,"736 14th St, New York City, NY 10001",8,August,New York City,NY,19,Thursday

In [61]:
# Create a Sales Column
df1['Sales'] = df1['Price Each']* df1['Quantity Ordered']

In [64]:
df1.describe()

,Quantity Ordered,Price Each,Month,Hour,Sales
count,185950.000000,185950.000000,185950.000000,185950.000000,185950.000000
mean,1.124383,184.399735,7.059140,14.413305,185.490917
std,0.442793,332.731330,3.502996,5.423416,332.919771
min,1.000000,2.990000,1.000000,0.000000,2.990000
25%,1.000000,11.950000,4.000000,11.000000,11.950000
50%,1.000000,14.950000,7.000000,15.000000,14.950000
75%,1.000000,150.000000,10.000000,19.000000,150.000000
max,9.000000,1700.000000,12.000000,23.000000,3400.000000

# **Data Visualisation**

In [68]:
import plotly.express as px

In [75]:
# Top States with Highest Sales

H_sales = df1['Sales'].groupby(df1['City']).sum().to_frame()

fig = px.bar(H_sales, x=H_sales.index, y='Sales', color='Sales', text='Sales')

fig.update_layout(title_text='States With Highest Sales',
                  title_x=0.5, title_font=dict(size=30))


fig.update_traces(textposition='outside', marker=dict(line=dict(color='#000000', width=2)))

In [85]:
# Month Sales  
M_sales = df1['Sales'].groupby(df1['Month Name']).sum().sort_values(ascending = False) .to_frame()

fig = px.bar(M_sales, x=M_sales.index, y='Sales', color='Sales', text='Sales')

fig.update_layout(title_text='Total Monthly Sales',
                  title_x=0.5, title_font=dict(size=30))


fig.update_traces(textposition='outside', marker=dict(line=dict(color='#000000', width=2)))

In [86]:
# Top Products Sold  
P_sales = df1['Sales'].groupby(df1['Product']).sum().sort_values(ascending = False) .to_frame()

fig = px.bar(P_sales, x=P_sales.index, y='Sales', color='Sales', text='Sales')

fig.update_layout(title_text='Total Products Sold',
                  title_x=0.5, title_font=dict(size=30))


fig.update_traces(textposition='outside', marker=dict(line=dict(color='#000000', width=2)))

In [93]:
# Customer Active Time
C_Time = df1['Order ID'].groupby(df1['Hour']).count() .to_frame()

fig = px.line(C_Time, x=C_Time.index, y='Order ID', title='Customer Active Time')
fig.show()